<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot_name">
  <!-- Define robot constants -->
  <xacro:property name="base_width" value="0.660"/>
  <xacro:property name="base_length" value="0.890"/>
  <xacro:property name="base_height" value="0.265"/>

  <xacro:property name="wheel_radius" value="0.10"/>
  <xacro:property name="wheel_width" value="0.38"/>

  <xacro:property name="wheel_ygap" value="-0.1"/>
  <xacro:property name="wheel_zoff" value="0.1"/>
  <xacro:property name="wheel_xoff" value="0.0"/>

  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint">
    <!-- Typically a frame, no collision geometry needed -->
  </link>

  <!-- Base link (frame only, no collision geometry added here) -->
  <link name="base_link">
  </link>

  <joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chasis"/>
    <origin xyz="0.0 0.0 0.055" rpy="0 0 0"/>
  </joint>

  <link name="chasis">
    <visual name="">
      <origin xyz="3.2 -0.32 0.0" rpy="${pi/2} 0.0 ${pi}"/>
      <geometry>
        <mesh filename="package://robot_description/src/meshes/chasis.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="">
        <color rgba="1.0 0.0 0.0 1.0"/>
        <texture filename=""/>
      </material>
    </visual>
    <collision name="collision">
      <!-- A simplified collision model as a box using the chassis dimensions.
           Adjust the origin as needed to match the physical center of mass. -->
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 ${pi}"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <!-- Wheels -->
  <xacro:macro name="wheel" params="prefix x_reflect y_reflect">
    <link name="${prefix}_link">
      <visual>
        <origin xyz="0.1 -0.02 -0.1" rpy="${pi/2} 0 ${pi}"/>
        <geometry>
          <mesh filename="package://robot_description/src/meshes/wheel.STL" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="Gray">
          <color rgba="0.5 0.5 0.5 1.0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0.1 -0.02 -0.1" rpy="${pi/2} 0 ${pi}"/>
        <geometry>
          <!-- Using a cylinder as a simplified collision model for the wheel -->
          <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${prefix}_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_link"/>
      <origin xyz="${-1*x_reflect*wheel_xoff} ${-1*y_reflect*(base_width/2+wheel_ygap)} ${wheel_zoff}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <xacro:wheel prefix="drivewhl_l" x_reflect="-1" y_reflect="-1" />
  <xacro:wheel prefix="drivewhl_r" x_reflect="-1" y_reflect="1" />

  <!-- ZED Camera Link -->
  <link name="zed_camera_link">
    <visual>
      <origin xyz="0 -0.1 0" rpy="0 0 ${pi/2}"/>
      <geometry>
        <mesh filename="package://robot_description/src/meshes/zed.STL" scale="0.001 0.001 0.001"/>
      </geometry>
      <material name="Gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <origin xyz="0 -0.1 0" rpy="0 0 ${pi/2}"/>
      <!-- A simple box collision approximating the camera's dimensions -->
      <geometry>
        <box size="0.15 0.15 0.1"/>
      </geometry>
    </collision>
  </link>

  <joint name="zed_camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="zed_camera_link"/>
    <!-- Adjust these values to match your real mounting position -->
    <origin xyz="0.4 0.03 0.17" rpy="0 0 0"/>
  </joint>


  <!-- <ros2_control name="RealRobot" type="system">
    <hardware>
        <plugin>motor_controller_pkg/MotorHardwareInterface</plugin>
        <param name="left_wheel_joint">drivewhl_l_joint</param>
        <param name="right_wheel_joint">drivewhl_r_joint</param>
        <param name="serial_port">/dev/ttyACM0</param>
        <param name="baud_rate">115200</param>
    </hardware>
    <joint name="drivewhl_l_joint">
        <command_interface name="velocity"/>
        <state_interface name="velocity"/>
    </joint>
    <joint name="drivewhl_r_joint">
        <command_interface name="velocity"/>
        <state_interface name="velocity"/>
    </joint>
</ros2_control> -->

</robot>
